### ISSUE TITLE
Add support for 38GL950G

### ISSUE THREAD

**Issue by fippse** [subraizada3/27gn950controller#11]
Hey, it would be awesome if you added support for the predecessor - which should be pretty similar to the 38GN950G. Currently, it just says 'not monitors found'. Cheerio!

**Comment by subraizada3** [comment]
Which OS are you using? Can you find the USB VID & PID of the monitor?

**Comment by fippse** [comment]
Hi, thank you. Windows 11. I think it is: VID: 043e, PID: 9a57 
I did a quick edit locally and it works with the monitor.

**Comment by subraizada3** [comment]
[This commit](https://github.com/subraizada3/27gn950controller/commit/00ab6d5c4cea0c2cd3fc806a68269d1ce9eb2235) should integrate that. Let me know if it works.

**Comment by subraizada3** [comment]
The latest version should now work with the 38GL with no modifications.

**Comment by subraizada3** [comment]
@fippse were you able to test this again on the 38GL950G?

**Comment by ghost** [comment]
@subraizada3 Yeah, awesome it works nicely!
