### ISSUE TITLE
27GN950-B support… Probably user error…

### ISSUE THREAD

**Issue by kierun** [subraizada3/27gn950controller#17]
I have a `27GN950-B` monitor. I tried to run the `./console.py info` (as `sudo`) and got 

`No monitors found`.

The monitor is there (I mean, I could not type this otherwise!) but it only connected via HDMI, not USB. Should I connect it via USB so I can use your code?

Thank you!

**Comment by subraizada3** [comment]
Yes, you need the USB connection.

HDMI/DisplayPort only carries the video signal to the monitor, LED control operates over the USB link (even with the official LG software).

**Comment by kierun** [comment]
… And as if by magic, everything works as soon as the USB is plugged in. Many thanks indeed for your code and time. Much appreciated.
