### ISSUE TITLE
Can't run script after updating to python 3.10

### ISSUE THREAD

**Issue by th347** [subraizada3/27gn950controller#21]
Thanks again for creating that script.
I've used it for a long time, but since I've updated to python 3.10 which I need to use for user scripts, I can't get the script running.
When I'm running console.py or gui.py the command window just closes instantly. Do you have any idea, what could fix this issue?

**Comment by AcheronTheFox** [comment]
Had same issue, now resolved.

Reinstalled earlier version of python but forgot to reinstall hid and pyqt5, in addition to leaving other called items out of same directory.
